import Head from "next/head";
import Banner from "./Components/Banner";
import Footer from "./Components/Footer";
import Header from "./Components/Header";
import LargeCard from "./Components/LargeCard";
import MeduimCard from "./Components/MeduimCard";
import SmallCart from "./Components/SmallCart";

export default function Home({ exploreData, cardsData }) {
  return (
    <div>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <main className=" max-w-7xl mx-auto px-8 md:px-16">
        <section className=" pt-6">
          <h2 className=" text-4xl font-semibold pb-5">Explore Nearby</h2>
        </section>
        <div className=" grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {exploreData?.map((item) => (
            <SmallCart
              key={item.img}
              img={item.img}
              location={item.location}
              distance={item.distance}
            />
          ))}
        </div>
        <section>
          <h2 className=" text-4xl font-semibold py-8">Live Anywhere</h2>
          {/* 牛逼 overflow-scroll */}
          <div className=" flex space-x-3 overflow-scroll scrollbar-hide p-3">
            {cardsData.map((item) => (
              <MeduimCard key={item.img} img={item.img} title={item.title} />
            ))}
          </div>
        </section>
        <section>
          <div>
            <LargeCard
              img="https://links.papareact.com/4cj"
              title="The Greatest Outdoors"
              description="Wishlists curated by Airbnb."
              buttonText="Get Inspried"
            />
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
export async function getStaticProps() {
  const exploreData = await fetch("https://www.jsonkeeper.com/b/4G1G").then(
    (res) => res.json()
  );
  const cardsData = await fetch("https://www.jsonkeeper.com/b/VHHT").then(
    (res) => res.json()
  );

  return {
    props: {
      exploreData,
      cardsData,
    },
  };
}
